language: python
python: "2.7"

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
      python-qt4

cache:
  directories:
    - lib/eco/pickle

install:
    - "pip install py"

script:
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ] ;
  then
     cd lib/eco; py.test test/test_eco.py --runslow ;
   else
     cd lib/eco; py.test test/test_eco.py ;
  fi
